CREATE DATABASE lab12
USE lab12;
CREATE TABLE Empolyee(
E_ID INT PRIMARY KEY IDENTITY(1,1),
E_name NVARCHAR(100) NOT NULL,
DOB DATE NOT NULL,
E_city NVARCHAR(100),
StreatAddress NVARCHAR(200),
BloodGroup NVARCHAR(100),
Cell INT NOT NULL,
Salary MONEY NOT NULL 
);